//
// Copyright © 2024 SHAO Liming <lmshao@163.com>. All rights reserved.
//

#include "rtsp_common.h"

std::map<StatusCode, std::string> StatusCodeReason = {
    {Continue, "Continue"},
    {OK, "OK"},
    {Created, "Created"},
    {LowOnStorageSpace, "Low on Storage Space"},
    {MultipleChoices, "Multiple Choices"},
    {MovedPermanently, "Moved Permanently"},
    {Found, "Found"},
    {NotModified, "Not Modified"},
    {UseProxy, "Use Proxy"},
    {BadRequest, "Bad Request"},
    {Unauthorized, "Unauthorized"},
    {PaymentRequired, "Payment Required"},
    {Forbidden, "Forbidden"},
    {NotFound, "Not Found"},
    {MethodNotAllowed, "Method Not Allowed"},
    {NotAcceptable, "Not Acceptable"},
    {ProxyAuthenticationRequired, "Proxy Authentication Required"},
    {RequestTimeout, "Request Timeout"},
    {Gone, "Gone"},
    {PreconditionFailed, "Precondition Failed"},
    {RequestMessageBodyTooLarge, "Request Message Body Too Large"},
    {RequestURITooLong, "Request-URI Too Long"},
    {UnsupportedMediaType, "Unsupported Media Type"},
    {ParameterNotUnderstood, "Parameter Not Understood"},
    {NotEnoughBandwidth, "Not Enough Bandwidth"},
    {SessionNotFound, "Session Not Found"},
    {MethodNotValidInThisState, "Method Not Valid in This State"},
    {HeaderFieldNotValidForResource, "Header Field Not Valid for Resource"},
    {InvalidRange, "Invalid Range"},
    {ParameterIsReadOnly, "Parameter Is Read-Only"},
    {AggregateOperationNotAllowed, "Aggregate Operation Not Allowed"},
    {OnlyAggregateOperationAllowed, "Only Aggregate Operation Allowed"},
    {UnsupportedTransport, "Unsupported Transport"},
    {DestinationUnreachable, "Destination Unreachable"},
    {DestinationProhibited, "Destination Prohibited"},
    {DataTransportNotReadyYet, "Data Transport Not Ready Yet"},
    {NotificationReasonUnknown, "Notification Reason Unknown"},
    {KeyManagementError, "Key Management Error"},
    {ConnectionAuthorizationRequired, "Connection Authorization Required"},
    {ConnectionCredentialsNotAccepted, "Connection Credentials Not Accepted"},
    {FailureToEstablishSecureConnection, "Failure to Establish Secure Connection"},
    {InternalServerError, "Internal Server Error"},
    {NotImplemented, "Not Implemented"},
    {BadGateway, "Bad Gateway"},
    {ServiceUnavailable, "Service Unavailable"},
    {GatewayTimeout, "Gateway Timeout"},
    {RTSPVersionNotSupported, "RTSP Version Not Supported"},
    {OptionNotSupported, "Option Not Supported"},
    {ProxyUnavailable, "Proxy Unavailable"},
};
